// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfaEcvlZ26Xbk5Nvd9-AXuGbe92yf1EV4',
    appId: '1:603113626118:web:535d62c6099518785a8187',
    messagingSenderId: '603113626118',
    projectId: 'autocare-728d0',
    authDomain: 'autocare-728d0.firebaseapp.com',
    storageBucket: 'autocare-728d0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8TzvRwU8O6Gn6yJ9-kINzsa9XWYVHAsM',
    appId: '1:603113626118:android:f59ca01c78cf8b015a8187',
    messagingSenderId: '603113626118',
    projectId: 'autocare-728d0',
    storageBucket: 'autocare-728d0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtuMu2YX1jxPCT9vbEGBRP3DIMKscQMjo',
    appId: '1:603113626118:ios:8c143000436c33795a8187',
    messagingSenderId: '603113626118',
    projectId: 'autocare-728d0',
    storageBucket: 'autocare-728d0.firebasestorage.app',
    iosBundleId: 'com.example.autocare',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtuMu2YX1jxPCT9vbEGBRP3DIMKscQMjo',
    appId: '1:603113626118:ios:8c143000436c33795a8187',
    messagingSenderId: '603113626118',
    projectId: 'autocare-728d0',
    storageBucket: 'autocare-728d0.firebasestorage.app',
    iosBundleId: 'com.example.autocare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfaEcvlZ26Xbk5Nvd9-AXuGbe92yf1EV4',
    appId: '1:603113626118:web:213dd1a2860a769c5a8187',
    messagingSenderId: '603113626118',
    projectId: 'autocare-728d0',
    authDomain: 'autocare-728d0.firebaseapp.com',
    storageBucket: 'autocare-728d0.firebasestorage.app',
  );
}
